The flag 'directory' used in rule all is only valid for outputs, not inputs.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 6
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	all
	2	bowtie2
	1	bowtie2_build
	2	fastp_se
	2	minimap2
	1	minimap2_index
	1	multiqc
	2	samtools_decontaminated
	1	woltka_classify
	1	woltka_gotu
	14
Select jobs to execute...

[Fri Dec 18 12:28:37 2020]
rule fastp_se:
    input: ../../../raw_fastqs/ERR2242499.fastq.gz
    output: ../results/QC_reads/ERR2242499_fastp.fastq, ../results/QC_reads/report/ERR2242499_fastp.html, ../results/QC_reads/report/ERR2242499_fastp.json
    log: ../results/logs/fastp/se/ERR2242499.log
    jobid: 2
    benchmark: ../results/benchmarks/fastp_se/ERR2242499.tsv
    wildcards: sample=ERR2242499
    threads: 6

[Fri Dec 18 12:29:08 2020]
Finished job 2.
1 of 14 steps (7%) done
Select jobs to execute...

[Fri Dec 18 12:29:08 2020]
rule fastp_se:
    input: ../../../raw_fastqs/ERR2242481.fastq.gz
    output: ../results/QC_reads/ERR2242481_fastp.fastq, ../results/QC_reads/report/ERR2242481_fastp.html, ../results/QC_reads/report/ERR2242481_fastp.json
    log: ../results/logs/fastp/se/ERR2242481.log
    jobid: 3
    benchmark: ../results/benchmarks/fastp_se/ERR2242481.tsv
    wildcards: sample=ERR2242481
    threads: 6

Terminating processes on user request, this might take some time.
[Fri Dec 18 12:29:26 2020]
Error in rule fastp_se:
    jobid: 3
    output: ../results/QC_reads/ERR2242481_fastp.fastq, ../results/QC_reads/report/ERR2242481_fastp.html, ../results/QC_reads/report/ERR2242481_fastp.json
    log: ../results/logs/fastp/se/ERR2242481.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 37 of /klaster/scratch/kkopera/COVID/microbiome/snakemake/QC_and_FT_advanced/polish-microbiome-project/shallow-shotgun-analysis-workflow/workflow/Snakefile:
Command 'set -euo pipefail;  /home/kkopera/.conda/envs/snakemake-2/bin/python3.6 /klaster/scratch/kkopera/COVID/microbiome/snakemake/QC_and_FT_advanced/polish-microbiome-project/shallow-shotgun-analysis-workflow/workflow/.snakemake/scripts/tmpeevbphji.wrapper.py' returned non-zero exit status 1.
  File "/home/kkopera/.conda/envs/snakemake-2/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2285, in run_wrapper
  File "/klaster/scratch/kkopera/COVID/microbiome/snakemake/QC_and_FT_advanced/polish-microbiome-project/shallow-shotgun-analysis-workflow/workflow/Snakefile", line 37, in __rule_fastp_se
  File "/home/kkopera/.conda/envs/snakemake-2/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/kkopera/.conda/envs/snakemake-2/lib/python3.6/concurrent/futures/thread.py", line 56, in run
  File "/home/kkopera/.conda/envs/snakemake-2/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/kkopera/.conda/envs/snakemake-2/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2351, in run_wrapper
Removing output files of failed job fastp_se since they might be corrupted:
../results/QC_reads/ERR2242481_fastp.fastq
Complete log: /klaster/scratch/kkopera/COVID/microbiome/snakemake/QC_and_FT_advanced/polish-microbiome-project/shallow-shotgun-analysis-workflow/workflow/.snakemake/log/2020-12-18T122836.953757.snakemake.log
